services:
  postgres:
    image: postgres:17.5-alpine
    restart: always
    container_name: postgresDev
    ports:
      - "5432:5432"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


# app:
#     build: .
#     depends_on:
#       db:
#         condition: service_healthy
#     ports:
#       - 8000:8000
#     environment:
#       AUTH_SECRET: <secret>
#       AUTH_URL: http://localhost:3000
#       DB_USER: postgres
#       DB_PASSWORD: postgres
#       DB_URL: postgresql://postgres:postgres@localhost:5432/postgres
#     networks:
#       - web-app