import Header from "@/components/layout/header";
import Providers from "@/components/providers";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import "@/styles/theme.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const generalSans = localFont({
	src: [
		{
			path: "../styles/fonts/GeneralSans-Variable.woff2",
			style: "normal",
		},
		{
			path: "../styles/fonts/GeneralSans-VariableItalic.woff2",
			style: "italic",
		},
	],
	variable: "--font-general-sans",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning className="h-full">
			<body
				className={cn(
					generalSans.variable,
					geistSans.variable,
					geistMono.variable,
					"font-general-sans antialiased"
				)}
			>
				<Providers>
					<div className="grid h-svh grid-rows-[auto_1fr]">
						<Header />
						{children}
					</div>
				</Providers>
			</body>
		</html>
	);
}
